source "https://rubygems.org"
gem "amazon_ssa_support",    ">0",    :require => "amazon_ssa_support",    :git => "https://github.com/ManageIQ/amazon_ssa_support.git",    :branch => "master"
gem "manageiq-gems-pending", ">0",    :require => "manageiq-gems-pending", :git => "https://github.com/ManageIQ/manageiq-gems-pending.git", :branch => "master"
gem "manageiq-smartstate",   "0.2.1", :require => "manageiq-smartstate"

# Modified gems for vmware_web_service.  Setting sources here since they are git references
gem "handsoap", "~>0.2.5", :require => false, :git => "https://github.com/ManageIQ/handsoap.git", :tag => "v0.2.5-5"
