source "https://rubygems.org"
gem "amazon_ssa_support",    :git => "https://github.com/ManageIQ/amazon_ssa_support.git",    :branch => "master"
gem "manageiq-gems-pending", :git => "https://github.com/ManageIQ/manageiq-gems-pending.git", :branch => "master"

# Modified gems for vmware_web_service.  Setting sources here since they are git references
gem "handsoap", "=1.4.0", :require => false, :source => "https://rubygems.manageiq.org"

# Load other additional Gemfiles
#   Developers can create a file ending in .rb under bundler.d/ to specify additional development dependencies
Dir.glob(File.join(__dir__, 'bundler.d/*.rb')).each { |f| eval_gemfile(File.expand_path(f, __dir__)) }
