---
name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
  - cron: 0 0 * * 0
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up registry credentials
      if: "${{ github.ref == 'refs/heads/master' && github.repository_owner == 'ManageIQ'
        }}"
      run: |
        echo "REGISTRY_USERNAME=${{ secrets.DOCKER_REGISTRY_USERNAME }}" >> $GITHUB_ENV
        echo "REGISTRY_PASSWORD=${{ secrets.DOCKER_REGISTRY_PASSWORD }}" >> $GITHUB_ENV
    - name: Run container build script
      run: bin/build_container_image
